[package]
name = "staking_hub"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
ic-cdk-timers = "0.6"
ic-stable-structures = "0.6"
serde = "1.0"
icrc-ledger-types = "0.1"
num-traits = "0.2"
